modLoader="javafml"
loaderVersion="36.2.0"
license="MIT"

[[mods]]
modId="flansmodultimate"
version="2.0-beta1"
displayName="Flan's Mod Ultimate 2"
logoFile="flansmod.png"
credits="All code contributors."
authors="Wolff, Jamioflan"
description='''Unofficial continuation of Flan's Mod to load content packs designed for legacy versions'''

[[dependencies.flansmodultimate]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flansmodultimate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flansmodultimate]]
    modId="flansmodultimate_packs"
    mandatory=false
    versionRange="[1,)"
    ordering="AFTER"
    side="BOTH"

mixins = [
    "flansmodultimate.mixins.json"
]