modLoader="javafml"
loaderVersion="36.2.0"
license="MIT"

[[mods]]
modId="flansmodultimate_packs"
version="1.0"
displayName="Content Packs for Flan's Mod Ultimate 2"
authors="Wolff"
displayTest = "NONE"
description='''This Mod adds armors from content packs designed for legacy Flan's Mod'''

[[dependencies.flansmodultimate_packs]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flansmodultimate_packs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
